### ISSUE TITLE
Icons in top right of graph modal

### ISSUE THREAD

**Issue by dtreich-itdp** [ITDP/atlas#88]
After expanding the 'graph' / 'compare' modal, it's not obvious that the user can click elsewhere on the screen to remove it. I suggest adding an X button to the top right.

Also, + is not the standard symbol to expand a window. I suggest something like one of these: https://www.flaticon.com/free-icons/expand-window

**Comment by kauebraga** [comment]
- I have added the X icon:

<img width="892" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/3ff2fa4f-8403-4bdd-98c1-50d856c7868a">



- I have included this icon to expand the window. It's easier to add this one because it's from a library we are already using, and I think it works fine
<img width="494" alt="image" src="https://github.com/ITDP/atlas/assets/22420248/d5582535-6d5f-4f99-87f2-14224fec098f">
